ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true

sys:
  config:
    value: prod123

spring:
  cloud:
    kubernetes:
      ribbon:
        mode: service
      discovery:
        enabled: true
      client:
        namespace: default
