apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}
