---
apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  type: NodePort
  ports:
    - name: http
      port: 30876
      protocol: TCP
      targetPort: 30876
      nodePort: 30876
  selector:
    app: config